POST http://localhost:8081/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzY0NjE2ODYsImV4cCI6MTYzNzMyNTY4Nn0.YnPmpSE9UFw7WUDa7bts0O29M1B7Q4Uz1uH_0Et16sZ5Wed-qio8tewh-YkjI96FqGYjOf6buCdGi6Ayz1HikA

{
  "name": "Oziq-ovqat"
}

###
GET http://localhost:8081/api/category
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzY0NjE2ODYsImV4cCI6MTYzNzMyNTY4Nn0.YnPmpSE9UFw7WUDa7bts0O29M1B7Q4Uz1uH_0Et16sZ5Wed-qio8tewh-YkjI96FqGYjOf6buCdGi6Ayz1HikA

###
PUT http://localhost:8081/api/category/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzY0NjE2ODYsImV4cCI6MTYzNzMyNTY4Nn0.YnPmpSE9UFw7WUDa7bts0O29M1B7Q4Uz1uH_0Et16sZ5Wed-qio8tewh-YkjI96FqGYjOf6buCdGi6Ayz1HikA

{
  "name": "MebelUpdated"
}

###
DELETE http://localhost:8081/api/category/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzY0NjE2ODYsImV4cCI6MTYzNzMyNTY4Nn0.YnPmpSE9UFw7WUDa7bts0O29M1B7Q4Uz1uH_0Et16sZ5Wed-qio8tewh-YkjI96FqGYjOf6buCdGi6Ayz1HikA

###

POST http://localhost/api/measurement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzg3NzIsImV4cCI6MTYzNjM5ODc3Mn0.-xGKM3tEHlb2wIa7VtaqTuFSBkemYIWjZTpU_na_odO6jYfNzwF19ahveTAbvhQmO1WBsNooNmu3rdNU3ezF4Q

{
  "name": "KG"
}

###
POST http://localhost/api/supplier
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzg3NzIsImV4cCI6MTYzNjM5ODc3Mn0.-xGKM3tEHlb2wIa7VtaqTuFSBkemYIWjZTpU_na_odO6jYfNzwF19ahveTAbvhQmO1WBsNooNmu3rdNU3ezF4Q

{
  "name": "Jafar"
}

###
POST http://localhost/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzg3NzIsImV4cCI6MTYzNjM5ODc3Mn0.-xGKM3tEHlb2wIa7VtaqTuFSBkemYIWjZTpU_na_odO6jYfNzwF19ahveTAbvhQmO1WBsNooNmu3rdNU3ezF4Q

{
  "name": "Huawei",
  "catId": 1,
  "measureId": 1
}


###
POST http://localhost:80/api/auth/login
Content-Type: application/json

{
  "userName": "912455897",
  "password": "123"
}

###super eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzU4NjY0MjYsImV4cCI6MTYzNTkwMjQyNn0.ckd4f4pvGm24oBMkGwt08fg7DD51qdl27RNCyd9iuqGdIe4VrWqwTwg87qTzm-NXrG8ztuSW_IqcUvL5FfsFoQ
###
#add warehouse
POST http://localhost:8081/api/warehouse
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzU4NjY0MjYsImV4cCI6MTYzNTkwMjQyNn0.ckd4f4pvGm24oBMkGwt08fg7DD51qdl27RNCyd9iuqGdIe4VrWqwTwg87qTzm-NXrG8ztuSW_IqcUvL5FfsFoQ

{
  "name": "Nomer3"
}

###
###get one byId
GET http://localhost:8080/api/product/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzU5MjE2MDcsImV4cCI6MTYzNjI4MTYwN30.6DLR-Cu0sjDryiulR8yp1_I0kpsEVsdew7s27eS4hUzaKtXBlzoTIgbGXTZpeMdi4KKR1-Het5J7kbmXf5OYaw

###
###get all
GET http://localhost:8080/api/product/allProduct
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzU5MjE2MDcsImV4cCI6MTYzNjI4MTYwN30.6DLR-Cu0sjDryiulR8yp1_I0kpsEVsdew7s27eS4hUzaKtXBlzoTIgbGXTZpeMdi4KKR1-Het5J7kbmXf5OYaw

###
POST http://localhost:80/api/input
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYyMTAxODMsImV4cCI6MTYzNjI5NjU4M30.blPmbto3VdGmg5C94Yovviir36haDMNp3otOGmcNnChYXE6FTlZimmLAkRoPp8sRUWCKRSUaTFGlSYEkVN5o1g

{
  "warehouseId": 1,
  "currencyId": 1,
  "factureName": "N11",
  "supplierId": 1,
  "inputProductDTOS": [
    {
      "productId": 3,
      "amount": 200,
      "price": 3000,
      "expireDate": "19-11-2021"
    },
    {
      "productId": 4,
      "amount": 10,
      "price": 50000,
      "expireDate": "17-10-2021"
    }
  ]
}


###get all
GET http://localhost/api/input/all?page=0&size=2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYyMTAxODMsImV4cCI6MTYzNjI5NjU4M30.blPmbto3VdGmg5C94Yovviir36haDMNp3otOGmcNnChYXE6FTlZimmLAkRoPp8sRUWCKRSUaTFGlSYEkVN5o1g

###get from to
GET http://localhost/api/input?from=05-11-2021&to=15-11-2021
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYyMTAxODMsImV4cCI6MTYzNjI5NjU4M30.blPmbto3VdGmg5C94Yovviir36haDMNp3otOGmcNnChYXE6FTlZimmLAkRoPp8sRUWCKRSUaTFGlSYEkVN5o1g

### get search
GET http://localhost:80/api/input/searchType?type=daily&date=04-11-2021
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYyMTAxODMsImV4cCI6MTYzNjI5NjU4M30.blPmbto3VdGmg5C94Yovviir36haDMNp3otOGmcNnChYXE6FTlZimmLAkRoPp8sRUWCKRSUaTFGlSYEkVN5o1g

###
POST http://localhost/api/measurement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzg3NzIsImV4cCI6MTYzNjM5ODc3Mn0.-xGKM3tEHlb2wIa7VtaqTuFSBkemYIWjZTpU_na_odO6jYfNzwF19ahveTAbvhQmO1WBsNooNmu3rdNU3ezF4Q

{
"name": "kg"
}

###
POST http://localhost:80/api/roles/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzY2MjgxODAsImV4cCI6MTYzNjcxNDU4MH0.7X5RjgEqmpcJ5J9ApUKrwI6xt6vNahVj6toZW33Bg8Pr6GXycvzBYz4Bdl0SEOL3LxNFkknFBG94o6b6i_kvzw

{

  "name": "new Role1",
  "active": true,
  "permission":
    [
      "ADD_USER",
      "EDIT_USER"
    ]
}
