GET http://localhost:1122/api/attachment/downloadFromDB/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzE2MjcsImV4cCI6MTYzNjA2NzYyN30.qm4PqbsuhP0P-dsq-BYwHrH79UkRgbtbD-DOC8N6xbKO3SDyuKg-9h-K1eO6E07u1ABEm7J_m2IIQxp0UqpxUw

###


###
POST http://localhost:1122/api/auth/login
Content-Type: application/json

{
  "userName": "912455897",
  "password": "123"
}

###super eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzE2MjcsImV4cCI6MTYzNjA2NzYyN30.qm4PqbsuhP0P-dsq-BYwHrH79UkRgbtbD-DOC8N6xbKO3SDyuKg-9h-K1eO6E07u1ABEm7J_m2IIQxp0UqpxUw
###
#add warehouse
POST http://localhost:1122/api/warehouse
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MTI0NTU4OTciLCJpYXQiOjE2MzYwMzE2MjcsImV4cCI6MTYzNjA2NzYyN30.qm4PqbsuhP0P-dsq-BYwHrH79UkRgbtbD-DOC8N6xbKO3SDyuKg-9h-K1eO6E07u1ABEm7J_m2IIQxp0UqpxUw

{
  "name": "Nomer2"
}





